### ISSUE TITLE
Recommendation 

### ISSUE THREAD

**Issue by stavros959** [kabouzeid/phonograph-issue-tracker#101]
Ohhh...Except from the bug , it would be a nice addition to press 3 times the headphone button to go to a previous track... (Actually it would be awesome if you included the number and feature of each click in the settings. See Sony's "Smart key" app to see what I mean.)

**Comment by stavros959** [comment]
*Include them in the settings. And..Except -from- ...Yea.. :P

**Comment by Xorok** [comment]
The titles you use should indicate what the report is about, not just "Serious bug!" or "Recommendation". This doesn't tell anything. Imagine everybody doing this. It would be a mess.

**Comment by TheDorkKnightRises** [comment]
I should think such button press options depend on your ROM and are not controlled by app. I may be wrong.
And agreed with Xorok above

**Comment by kabouzeid** [comment]
See https://github.com/kabouzeid/phonograph-issue-tracker/issues/26
