### ISSUE TITLE
Suggestion: Album sort by artist 

### ISSUE THREAD

**Issue by Sentim** [kabouzeid/phonograph-issue-tracker#118]
Could you add the ability to sort albums by artist name?

**Comment by EgonSpengler** [comment]
+1

My main usage of a media player is to shuffle, and occasionally turning off shuffle when I get to an artist I want to hear more of.  This sort of behavior is much easier when, for instance, I can choose which tag to sort by in the "songs" view.  Then, selecting play/shuffle all will create a playlist in that order, which can be shuffled or played sequentially.

The equivalent in this request would be to sort albums by artist or album artist, with the addition of a "play all" button to this view as well.

**Comment by kabouzeid** [comment]
see https://github.com/kabouzeid/phonograph-issue-tracker/issues/15
