### ISSUE TITLE
Playback Card in Status Bar Menu

### ISSUE THREAD

**Issue by ECHLN** [kabouzeid/phonograph-issue-tracker#122]
Can you please change the current one to something that matches the new look of the app? Make it white with a clean look because this grey really looks outdated when looking at other cards in the menu.

**Comment by kabouzeid** [comment]
It's the same color as other notifications, is it?

**Comment by ECHLN** [comment]
This is extremely embarrassing. I thought I was reporting to the Soundcloud app. Sorry about this.

**Comment by kabouzeid** [comment]
Never mind :D
