### ISSUE TITLE
(Bug) Empty song appers in songs, albums and artists

### ISSUE THREAD

**Issue by drt0** [kabouzeid/phonograph-issue-tracker#131]
The picture of the 'album' says sdcard write work-around and the song title is {MediaWrite Workaround} as seen here:
http://puu.sh/m2lAD/e90b1c028a.jpg

This is how it looks in albums and in artists:
http://puu.sh/m2lB2/71be1cf058.jpg
http://puu.sh/m2lBj/df0004b8d6.jpg

**Comment by kabouzeid** [comment]
This seems like a bug with android media store. I don't think I can fix that, sorry.
