### ISSUE TITLE
SUGGESTION: skip songs through the cover art and some design points

### ISSUE THREAD

**Issue by gbbraganholo** [kabouzeid/phonograph-issue-tracker#133]
One of the things I miss the most, since I first installed the app is the ability to skip songs by dragging them to the sides, as many of the others players do.
The equalizer is another.
Design wise, I think the shadow under the song-title bar is way too pronounced, it's too heavy. The now-playing page needs some cleaning in the matter of information displayed, there's too much separation of the information. Does it make sense? Haha
Another thing that bothers me is the lack of an option to choose a fixed color to the now-playing page, and the album-title bar. It's ok many people like it changing with the cover colors, but not everyone, so it would be nice to have the option to fix it like we do with the general theme and details.
The font of the little bar when you minimize the now-playing page needs to be the same as the general font type.

For now, that's the contribution I have. I'll let you know if something else pops up.
Congrats for the app!

**Comment by kabouzeid** [comment]
Thanks for your suggestions, next time put every thing in its own issue. Also pls search for duplicates before you post. I have most of the the thing you mentioned covered in the next update :)
