### ISSUE TITLE
Feature Request : Google Music + OneDrive integration

### ISSUE THREAD

**Issue by muushfiqq** [kabouzeid/phonograph-issue-tracker#134]
If Phonograph could play/stream songs directly from cloud then it could be awesome. Google Music integration, OneDrive integration for music would be a fantastic edition to Phonograph. 

Another thing, when will it support lastfm scrobbling ?.

Lastly, thanks for creating a great music player !

**Comment by kabouzeid** [comment]
Google and OneDrive support won't come, sorry.

Last.fm support is already there. Just install the official last.fm app and login with your account :)
