### ISSUE TITLE
New Lockscreen Buttons 

### ISSUE THREAD

**Issue by Aphiwe778** [kabouzeid/phonograph-issue-tracker#198]
I can't change songs nor stop them 😳 

Device info:
---
<table>
<tr><td>App version</td><td>0.14.0 BETA 1</td></tr>
<tr><td>App version code</td><td>126</td></tr>
<tr><td>Android build version</td><td>J100HXXU0APD1</td></tr>
<tr><td>Android release version</td><td>4.4.4</td></tr>
<tr><td>Android SDK version</td><td>19</td></tr>
<tr><td>Android build ID</td><td>KTU84P.J100HXXU0APD1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>j13g</td></tr>
<tr><td>Device model</td><td>SM-J100H</td></tr>
<tr><td>Device product name</td><td>j13gxx</td></tr>
<tr><td>Device hardware name</td><td>sc8830</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>null</td></tr>
<tr><td>ABIs (64bit)</td><td>null</td></tr>
</table>

**Comment by arkon** [comment]
Does this still happen?

**Comment by Aphiwe778** [comment]
not at all after the latest version it's back to normal on the now
playing is nuisance now .Please reduce the Up Next Panel it takes up
the space intended for the album art please

**Comment by arkon** [comment]
The album art simply takes up a square's worth of space. If your device's screen size is small, that may affect it, but it's not a bug.

**Comment by Aphiwe778** [comment]
Oh thank, I hope more Now Playing Screens are on the way sir



Sent from my Samsung Galaxy smartphone.

-------- Original message --------
