### ISSUE TITLE
Toolbar menu items in now playing view are hard to hit. The sliding panel closes instead of performing the action when clicking to far on top of the items.

### ISSUE THREAD

**Issue by ChazW** [kabouzeid/phonograph-issue-tracker#21]

**Comment by ChazW** [comment]
It is a little bit annoy

**Comment by BohemianRahpGod** [comment]
What settings button?

**Comment by ChazW** [comment]
when press the buttons then u can see the sleep timer thing

**Comment by ChazW** [comment]
when i click a little bit above it on my nexus 5 lollipop，it minize the playing interface as if i did the swipe down gesture.

**Comment by kabouzeid** [comment]
I know what you mean, I will fix that in future.

**Comment by ChazW** [comment]
Thank you

**Comment by Ualace** [comment]
In my case is almost impossible, cause I have to hint a very specific point for it works.

**Comment by JuBarros** [comment]
Same problem with my galaxy win! I'm about to un install this app, love it, but this problem is completely annoying
