### ISSUE TITLE
Support for the Apple Lossless Audio Codec (ALAC)

### ISSUE THREAD

**Issue by vrwsyjbl** [kabouzeid/phonograph-issue-tracker#216]
The Apple Lossless Audio Codec (ALAC) was open-sourced in October 2011 under the Apache License 2.0. While native support for this codec isn't included in current versions of Android, would it be possible to add support for it to Phonograph? For users such as myself with large libraries encoded in this format, it would be very useful to be able to play such files in Android. It would also be a useful feature that would further set Phonograph apart from much of the competition. Would it be possible to add support for this codec to a future version of the app?

Thanks for all the hard work in producing such a great app!

**Comment by lsmgeb89** [comment]
I have the same request. Actually, Poweramp suppots this, but its UI is worse than Photography.

**Comment by Kat-Hub** [comment]
I'm using a Asus Zenfone 2 and Phonograph in my phone supports ALAC flawlessly.

**Comment by kabouzeid** [comment]
There wont be custom audio formats. Either your device natively supports the file format or not. I'm not going to write my own media player engine as poweramp did.
