### ISSUE TITLE
[Enhancement] Increase the blur effect of album art

### ISSUE THREAD

**Issue by andrh1** [kabouzeid/phonograph-issue-tracker#241]
I really like the feature that blurs the album art as my LG G4 uses them as wallpaper when music is playing. The current blur is a great start however my lockscreen still looks busy and unpleasant as the blur isn't strong enough to remove sufficient detail. 

Example 1:
Without blur: http://imgur.com/hNfrhFY.jpg
With current blur: http://imgur.com/41nNRLr.jpg
With proposed blur: http://imgur.com/B2NkbbM.jpg

Example 2:
Without blur: http://i.imgur.com/VK8VTA4.png
With current blur: http://i.imgur.com/LM87QGe.png
With proposed blur: http://i.imgur.com/bFVE7Dx.png

**Comment by kabouzeid** [comment]
Nah, I think this is too much. You could also completely disable the album art on the lock screen.
