### ISSUE TITLE
[Feature Request] Last.fm scrobbling

### ISSUE THREAD

**Issue by RubenRME** [kabouzeid/phonograph-issue-tracker#245]
I would like to see last.fm scrobbling either in the app itself, or "Simple last.fm scrobbler" support.
If this is added Phonograph will become my default music app :)

**Comment by kabouzeid** [comment]
YOu can just install the official last.fm app from Google Play. It will work out of the box.

**Comment by RubenRME** [comment]
Did not knew that! Thanks for the response, but even more thanks for the app!
