### ISSUE TITLE
[Bug] song or album title not correctly encoded

### ISSUE THREAD

**Issue by DVDAndroid** [kabouzeid/phonograph-issue-tracker#248]
![screenshot_20160209-112710 2](https://cloud.githubusercontent.com/assets/6277172/12921721/bde7d160-cf4e-11e5-8e7a-232c7eb3bd61.png)

**Comment by kabouzeid** [comment]
that should be up to androids media store. Does it happen with Shuttle Music Player?

**Comment by DVDAndroid** [comment]
![screenshot_20160209-172908 2](https://cloud.githubusercontent.com/assets/6277172/12922730/ee0f5f30-cf52-11e5-9c97-8c924e9bafc7.png)

Yes

**Comment by kabouzeid** [comment]
Sorry, but I won't be able to fix it then. You could try to find out how to fix your devices media store to correctly read the tags :)

**Comment by DVDAndroid** [comment]
Ok, thanks for the help
