### ISSUE TITLE
Pause and Play button animation was bug On Asus Zenfone t00i

### ISSUE THREAD

**Issue by Ichijouurakuu** [kabouzeid/phonograph-issue-tracker#259]
Every i click pause or play button from now playing the animation of pause and play button stoped..so please fix it..

**Comment by Rishab2oo** [comment]
This is happening On Lenovo a6000 plus (KitKat) too. I updated just now with the latest update and it hasn't fixed the problem.

**Comment by kabouzeid** [comment]
#246

**Comment by AgathoN** [comment]
Made a quick video
https://youtu.be/LlkUut26TE0
