### ISSUE TITLE
Add tripple press headphone button to rewind support

### ISSUE THREAD

**Issue by musfiqus** [kabouzeid/phonograph-issue-tracker#26]
Tripple press to rewind is one really important feature, specially for those travel by crowded bus or train like me. It's really difficult to put the phone out of pocket in those situations if you have mistakenly slipped a song. Please add this feature if possible.

**Comment by kabouzeid** [comment]
Good idea

**Comment by musfiqus** [comment]
Hi, any update on this?

**Comment by kabouzeid** [comment]
No, I'm currently quite busy :(

**Comment by DVDAndroid** [comment]
@kabouzeid I think you can close this issue :+1:

**Comment by kabouzeid** [comment]
It's so hard to keep up to date with this issue tracker. Many duplicated and/or unread issues.
