### ISSUE TITLE
Song Metadata Special Character Display Issue

### ISSUE THREAD

**Issue by niklasbogi** [kabouzeid/phonograph-issue-tracker#266]
A song in my library containing the letter "**_á_**" in its album metadata is displayed incorrectly in album/artist view and the notification (see attached pictures). It is displayed just fine in tag editor view (see pictures as well).
This does not happen with other songs containing characters with accent marks such as "ó".
The song is an AAC file edited with iTunes on Mac, the character is a standard latin "a" with an "´". My phone is a OnePlus One with CyanogenMod 12.1, however no custom fonts are installed.

![screenshot_2016-02-20-00-47-23](https://cloud.githubusercontent.com/assets/8931810/13381120/97442874-de53-11e5-9339-e99bbabcfd13.png)
![screenshot_2016-02-20-00-48-38](https://cloud.githubusercontent.com/assets/8931810/13381128/e91877e0-de53-11e5-9adc-51f0af30886b.png)
![screenshot_2016-02-20-00-47-32](https://cloud.githubusercontent.com/assets/8931810/13381122/a3750dfc-de53-11e5-99ff-4bc1362aed1b.png)

**Comment by DVDAndroid** [comment]
Duplicate of #248

**Comment by niklasbogi** [comment]
Sorry, I didn't find DVDAndroid's already-closed issue before, maybe I'll try updating to Marshmallow and see if that fixes the Media Store corruption.
Consider this closed.
