### ISSUE TITLE
Fix the "double album" bug

### ISSUE THREAD

**Issue by MasiaVittorio** [kabouzeid/phonograph-issue-tracker#32]
In some music players i don't find this problem, but in phonograph (as in Google play music, or in the musixmatch player, for example) some albums of mine are splitted in two parts.

**Comment by kabouzeid** [comment]
Thats a media store or tagging issue. Can't fix that in both cases

**Comment by MasiaVittorio** [comment]
Poweramp (like also black player for example) doesn't have this problem.
Can't you make your app recognize only the "album tag"? Because in my songs
the album has the exact same name, but for some reason the library split
them in two separated album with that name and artist. I don't know if the
different "genre" tag can be the cause of the issue..
Il 13/set/2015 15:13, "Karim Abou Zeid" <notifications@github.com> ha
scritto:

**Comment by kabouzeid** [comment]
Thats because they are using custom media providers, and I'm not willing to do that.
