### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by CrisWebb** [kabouzeid/phonograph-issue-tracker#33]
Sometimes, while I move the application to choose a song, the application stops.

Device; Moto G 1st XT1032
OS version; Android Lollipop 5.1

Thanks, dude.

**Comment by kabouzeid** [comment]
Sorry dude, thats to less information to work with, could be anything and might be fixed in future by accident.

**Comment by CrisWebb** [comment]
I know the information is limited, but there is nothing more to say (I think) just the application stops. Regardless, thanks for your work.
