### ISSUE TITLE
Progress slider jumps back after selection

### ISSUE THREAD

**Issue by Xorok** [kabouzeid/phonograph-issue-tracker#36]
https://vid.me/Ktsa

**Comment by Xorok** [comment]
HTC One M8 running Android 5.0.1

**Comment by kabouzeid** [comment]
This song only, or all songs?

**Comment by Xorok** [comment]
With all songs from this Album. They're 24bit FLAC's: http://postimg.org/image/bx3sujlrj/

**Comment by Xorok** [comment]
Doesn't happen with 16bit FLAC's.

**Comment by Xorok** [comment]
But it's not that high-priority. I mean, which normal person uses 24bit FLAC's on their devices (and frequently jumps between certain times)? No wonder this happens. Much more data to process.

**Comment by Xorok** [comment]
*devices = mobie phones

**Comment by kabouzeid** [comment]
This seems like an Android Media Player problem. I think I cant fix that, sorry :/
