### ISSUE TITLE
Album year shown as "0" in the Artist view when the album is in another format than .mp3

### ISSUE THREAD

**Issue by Siphonay** [kabouzeid/phonograph-issue-tracker#39]
Hello !
First of all, thank you for your work on Phonograph. It's truly awesome and I think I'm gonna stick with it for at least a little while.

However,I'm encountering an issue. When I view an artist on the artist tab, albums that are not in the .MP3 format (as I also use .FLAC and .OGG) years are shown as "0", even if they are tagged correctly, as seen in the tag editor.

Here are some screenshots :
![Muse artist view](http://img.siphonay.fr/up/Screenshot_2015-09-16-15-02-46.png)
![Drones album view](http://img.siphonay.fr/up/Screenshot_2015-09-16-15-02-56.png)
![Sonata Arctica artist view](http://img.siphonay.fr/up/Screenshot_2015-09-16-15-04-10.png)
![Pariah's Child album view](http://img.siphonay.fr/up/Screenshot_2015-09-16-15-13-36.png)

I didn't try on other android devices though.
If this information is releavant, my device is an HTC One M7 with Android 5.0.1.

Thank you for your attention, and again, thanks for Phonograph, keep up your great work !

**Comment by kabouzeid** [comment]
This is Android Media stores fault. You might don't get why, but believe me, it would cause other problems. So unfortunately probably wont fix.

**Comment by Siphonay** [comment]
I understand. I'm having trouble with other music player that uses Android's library. It's awful how buggy it is and how it has not improved since Gingerbread !
Thanks for your attention.

**Comment by kabouzeid** [comment]
Yeah, its really a shame :/

**Comment by benoliver999** [comment]
Is is this also why embedded album art is not displayed for FLAC, but works fine with MP3s? I have tested it in this app, Timber and Shuttle with no joy (the latter worked, but because it downloaded the art).

**Comment by kabouzeid** [comment]
@benoliver999 jep
