### ISSUE TITLE
Music playback issue when screen is off. 

### ISSUE THREAD

**Issue by sax0406** [kabouzeid/phonograph-issue-tracker#41]
I'm using the version 0.9.46 beta3. Whenever I play any song (the screen will be off), it stops the playback when the current song ends. I have tried waiting for a long time for the next song to play, but it doesn't happen. When I switch on the screen, the next song starts playing.

**Comment by sax0406** [comment]
P.S. I'm using oneplus one with AOSParadox rom. AudioFX or MaxxAudio are not installed.

**Comment by kabouzeid** [comment]
Can't reproduce. Also OnePlus One here. Anyone else?

**Comment by german6** [comment]
I'm having the same issue. I have a Moto G1 (not rooted).

**Comment by sax0406** [comment]
I noticed that it happens only when you start playing a song when the screen is off. I usually plug in my headset and start playing the song by pressing the headset button. In this case, the next song doesn't play. One more scenario is if I pause the song when the screen is off and start it again, both using the headset button, the next song doesn't play until I switch on the screen.

**Comment by kabouzeid** [comment]
@sax0406 I just tried both scenarios. Works like a charm for me...

**Comment by german6** [comment]
@sax0406 this is not possible for me because I have no headset. I just play it normally and sometimes that happens.

**Comment by bantot123** [comment]
Hi this issue is also occurring with me. LG G2 and music stops playback at the end of songs randomly. To get the next song to play I just need to open the screen.

**Comment by kabouzeid** [comment]
Must be something like Greenify or an other battery safer app. Can't reproduce on any of my devices.
