### ISSUE TITLE
Landscape mode for the Now-Playing screen

### ISSUE THREAD

**Issue by Xorok** [kabouzeid/phonograph-issue-tracker#44]
Please consider bringing back the landscape mode. Not every device has a 5.5" screen and the current setup looks really awkward on the majority of devices (4.7"-5.2").

http://www11.pic-upload.de/18.07.15/pft8brnjmug5.png
http://www11.pic-upload.de/18.09.15/gd1nln3oym9u.png

**Comment by Xorok** [comment]
Better for comparison: http://www11.pic-upload.de/18.09.15/hfaixclce2h.png

HTC One M8 (5")

**Comment by Siphonay** [comment]
I could not agree more. Really feels like most of the screen space is wasted.

**Comment by shaft17** [comment]
I loved the old landscape layout from 9.9.2b... maybe an option?
http://i.imgur.com/qs41ITS.png

**Comment by kabouzeid** [comment]
@shaft17 there will be something better soon :)
