### ISSUE TITLE
Metadata / Tags not being read from .m4a files

### ISSUE THREAD

**Issue by CampAsAChamp** [kabouzeid/phonograph-issue-tracker#47]
All of my .m4a from iTunes don't have any metadata/tags on them even though there is data for the artist, album, etc.

Here is an example
![screenshot_2015-09-20-19-31-39](https://cloud.githubusercontent.com/assets/13057262/9984564/ce38f9b2-5fce-11e5-8d57-66f282848a40.png)
![screenshot_2015-09-20-19-31-53](https://cloud.githubusercontent.com/assets/13057262/9984565/ce393396-5fce-11e5-817d-de17d2eb4e93.png)

**Comment by kabouzeid** [comment]
Thats Android Media Stores issue.
