### ISSUE TITLE
FAB stops over the next button when opening the the NP screen. Also, the bottom, even when the bottom bar is disabled, never goes away, staying translucent at the top of the NP screen.

### ISSUE THREAD

**Issue by BohemianRahpGod** [kabouzeid/phonograph-issue-tracker#5]

**Comment by kabouzeid** [comment]
@BohemianRahpGod you mean this?
![9f807cd4-53c2-11e5-930a-59f56de43c9b](https://cloud.githubusercontent.com/assets/7303830/9706302/8a3727f4-54e1-11e5-8bb4-b0c72c1a1cec.png)

**Comment by BohemianRahpGod** [comment]
Yup

**Comment by kabouzeid** [comment]
@BohemianRahpGod that was fast, lol

**Comment by BohemianRahpGod** [comment]
Thinkn the same thing

**Comment by kabouzeid** [comment]
So does that only happen when the bottom bar is disabled? I am actually trying to fix that since a few days, but I have made no progress yet, because I cant reproduce...

**Comment by BohemianRahpGod** [comment]
No, doesn't matter, disabled, or enabled

**Comment by BohemianRahpGod** [comment]
Imma go through the settings that affects athstetics, and report back

**Comment by kabouzeid** [comment]
Would be great, even though I don't think it will make a difference...

**Comment by kabouzeid** [comment]
Device and Android version? Also XPosed (if yes which modules) and or other root apps installed?

**Comment by BohemianRahpGod** [comment]
Stock ROM, Moto G 2014, 5.0.1

**Comment by BohemianRahpGod** [comment]
This is the newest version BTW

**Comment by kabouzeid** [comment]
I think everyone who have that issue said they are using a Moto G. Must be some weird Motorola stuff. I will see if I can borrow a friends Moto G for debugging sometime soon.

**Comment by kabouzeid** [comment]
Can you remember it worked before anytime since we had that sliding panel?

**Comment by BohemianRahpGod** [comment]
Well I've disabled most Motorola apps, which don't even really make any changes, and Motorola uses stock android, so it would have to be hardware. This didn't happen to me prior to the latest update either

**Comment by kabouzeid** [comment]
Do you remember which version was it exactly?

**Comment by BohemianRahpGod** [comment]
0.9.44 beta5 is current, but I think beta3 or beta4 was good

**Comment by kabouzeid** [comment]
Do you have time so that I send you debug apk's and you tell me if it got better or worse?

**Comment by BohemianRahpGod** [comment]
How bout you send one from a week and a half ago

**Comment by BohemianRahpGod** [comment]
Also just went through all the settings, nothing changes

**Comment by kabouzeid** [comment]
http://www.apkmirror.com/apk/kabouzeid/gramophone/phonograph-0-9-43b-beta1-android-apk-download/

**Comment by kabouzeid** [comment]
You will have to uninstall the current version first

**Comment by BohemianRahpGod** [comment]
np
will report back

**Comment by BohemianRahpGod** [comment]
thx dork night

**Comment by BohemianRahpGod** [comment]
Yep it's good

**Comment by BohemianRahpGod** [comment]
What is it beta4?

**Comment by kabouzeid** [comment]
no, thats beta 1

**Comment by BohemianRahpGod** [comment]
oh

**Comment by BohemianRahpGod** [comment]
well, it works

**Comment by kabouzeid** [comment]
so its really working in beta 1?

**Comment by kabouzeid** [comment]
weird...

**Comment by kabouzeid** [comment]
ok wait a second

**Comment by BohemianRahpGod** [comment]
send me a beta3 and see if it's tstill good

**Comment by kabouzeid** [comment]
No need to try that. I know what is different between the old and the current implementation. But I want to keep the current implementation as it is much cleaner and faster.

**Comment by kabouzeid** [comment]
Please try this version and send me screen shots from the sliding panel half and fully opened.
 https://drive.google.com/file/d/0B3MVI9GVpB_udjNFZkVnMlF2RzA/view?usp=sharing

**Comment by BohemianRahpGod** [comment]
What do you mean sliding panel

**Comment by kabouzeid** [comment]
sliding the bottom bar up and down to expand or collapse the player

**Comment by BohemianRahpGod** [comment]
https://goo.gl/photos/cTPV4L9FmRpfxRF88
https://goo.gl/photos/1CXTcYtFQUhf1kg69

**Comment by kabouzeid** [comment]
Ok now this is really really really weird. I didn't expect that. Makes no sense to me.

**Comment by BohemianRahpGod** [comment]
hmm

**Comment by kabouzeid** [comment]
But don't worry, I will find a solution for that.

**Comment by BohemianRahpGod** [comment]
Cool. If you need anything else just ask

**Comment by kabouzeid** [comment]
I will need your help again soon enough :b

**Comment by BohemianRahpGod** [comment]
noith

**Comment by kabouzeid** [comment]
But I need some sleep now, see you then

**Comment by BohemianRahpGod** [comment]
cool, cya

**Comment by kabouzeid** [comment]
I know this is ugly, but try this and just tell me if everything moves to the right place now.

https://drive.google.com/file/d/0B3MVI9GVpB_uVzlPZE1BTGc1S3M/view?usp=sharing

**Comment by BohemianRahpGod** [comment]
I will in a sec

**Comment by BohemianRahpGod** [comment]
I pressed download, it downloaded, can't open file

**Comment by BohemianRahpGod** [comment]
I'm getting a debug.apk.apk

**Comment by kabouzeid** [comment]
sorry, wrong link, try again now

**Comment by BohemianRahpGod** [comment]
np, whats the link

**Comment by kabouzeid** [comment]
I've updated the comment

**Comment by kabouzeid** [comment]
https://drive.google.com/file/d/0B3MVI9GVpB_uTWFEUy1ONzZjRGs/view?usp=sharing

**Comment by BohemianRahpGod** [comment]
That's works, did you just slow down the transition speed?

**Comment by BohemianRahpGod** [comment]
This happens though https://goo.gl/photos/E9VpMiUsHSLugiSX7

**Comment by kabouzeid** [comment]
yeah, thats normal, don't mind

**Comment by BohemianRahpGod** [comment]
okey

**Comment by kabouzeid** [comment]
It was actually not meant as a fix but I've been trying out something. I will have to think about what I'm gonna do next now. Well after I finally found some sleep ^^

**Comment by BohemianRahpGod** [comment]
Okey, is okay to revert to beta now?

**Comment by kabouzeid** [comment]
I actually recommend you to do so :b

**Comment by kabouzeid** [comment]
@BohemianRahpGod I think I have fixed it. Please try, and let me know if it works. https://drive.google.com/file/d/0B3MVI9GVpB_uUEtxZTRVRDhTbG8/view?usp=sharing

**Comment by BohemianRahpGod** [comment]
Sorry I'm late, I'll try it and check back

**Comment by BohemianRahpGod** [comment]
GOAL

**Comment by BohemianRahpGod** [comment]
It works

**Comment by kabouzeid** [comment]
Ok thanks, I will push the update soon then :)
