### ISSUE TITLE
Shuffle button in now playing becomes hard to tell

### ISSUE THREAD

**Issue by xiprox** [kabouzeid/phonograph-issue-tracker#51]
The shuffle button in the now playing screen may become hard to tell apart if the generated accent color is close to the default color. While I don't have an instant solution in mind, a worst case solution could be to display Toast messages every time shuffle status changes.

EDIT: This applies to the repeat button too.

**Comment by kabouzeid** [comment]
I tried the toast before. It was really annoying...

**Comment by xiprox** [comment]
I can imagine. How about comparing the luminance of the default color with the luminance of the generated color, and if they are very similar, increasing the luminance of the generated color a bit? (Not sure how this would work. I'm not very knowledgeable about these stuff either.)

**Comment by kabouzeid** [comment]
I also had something like this in mind. But the code in this place is already really cluttered and complex and to be honest its not my highest priority right now.

**Comment by xiprox** [comment]
I see. But then again, you really can't tell whether shuffle is on or off with grey colors until you skip a few tracks back and forth.

**Comment by xiprox** [comment]
Experimentation shows that it isn't possible to make judgements based on luminance. Dark red for example, may have a luminance value less than a grey color.

**Comment by xiprox** [comment]
The app will now check for the difference between the default and the generated colors. If the two colors are found to be close to each other, the generated color will be made slightly darker.
