### ISSUE TITLE
Removing a previous item from queue messes the queue up

### ISSUE THREAD

**Issue by xiprox** [kabouzeid/phonograph-issue-tracker#52]
Removing a previous item from the playing queue messes up now playing.

**Example scenario:**
We have the following queue:
- Song A
- :speaker: Song B
- Song C
- Song D

We remove Song A. The queue now becomes:
- Song B (actually playing)
- :speaker: Song C
- Song D

When the song finishes or the user manually skips to the next one, Song C is avoided and Song D is played.

Also, if you navigate away from the app and reopen it (without stopping playback), you can see that the now playing screen itself displays the album art and info of Song C, when the song actually being played is Song B.

**Comment by kabouzeid** [comment]
Fixed in latest commit
