### ISSUE TITLE
Year fields in album tiles in artist pages are sometimes zero

### ISSUE THREAD

**Issue by Wulgaren** [kabouzeid/phonograph-issue-tracker#55]

**Comment by xiprox** [comment]
Which year bug are you referring to? Add some details please.

**Comment by Wulgaren** [comment]
When i click on artist i see some albums that have year 0 under them, even
if they have for example 2010 in tags.
26 wrz 2015 10:51 "İhsan Işık" <notifications@github.com> napisał(a):

**Comment by Siphonay** [comment]
I already submitted this issue, but it was closed : https://github.com/kabouzeid/phonograph-issue-tracker/issues/39
