### ISSUE TITLE
Swipe artwork to change tracks

### ISSUE THREAD

**Issue by mburningstariv** [kabouzeid/phonograph-issue-tracker#59]
This is needed. This should be a given in a music app, especially the (otherwise) best music app on Android. We can currently swipe the bottom bar to change tracks, but it needs the ability to swipe the artwork in the actual Now Playing screen. It's been requested by a huge amount of users and there's never any acknowledgement. Can we please see this implemented soon?

**Comment by kabouzeid** [comment]
Yes I kept that in my mind and it will be implemented, but as this requires a lot of work and I don't have much time right now, you will have to wait for it a bit.
