### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by Aphiwe778** [kabouzeid/phonograph-issue-tracker#61]
Layout Like Apple Music Music Player 

-

Device info:
---
<table>
<tr><td>App version</td><td>0.13.0 BETA 4</td></tr>
<tr><td>App version code</td><td>114</td></tr>
<tr><td>Android build version</td><td>G318HJVU0APA2</td></tr>
<tr><td>Android release version</td><td>4.4.4</td></tr>
<tr><td>Android SDK version</td><td>19</td></tr>
<tr><td>Android build ID</td><td>KTU84P.G318HJVU0APA2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>vivalto3mveml3g</td></tr>
<tr><td>Device model</td><td>SM-G318H</td></tr>
<tr><td>Device product name</td><td>vivalto3mveml3gxx</td></tr>
<tr><td>Device hardware name</td><td>sc8830</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>null</td></tr>
<tr><td>ABIs (64bit)</td><td>null</td></tr>
</table>

**Comment by kabouzeid** [comment]
No, sorry.

**Comment by Aphiwe778** [comment]
Can Drop The Now Playing Bar Then It Smaller Phones it's seems every not nice
