### ISSUE TITLE
Request to add more personalization

### ISSUE THREAD

**Issue by prateeklohchubh** [kabouzeid/phonograph-issue-tracker#65]
1. Option to remove tabs such as playlists or songs
2. Option to change view of artist pane similar to shuttle. 
3. In artist view please change title color to the choosen theme/accent color rather than taking it from artist image. 
4. Option to speed up animations in now playing.

**Comment by kabouzeid** [comment]
An issue should only contain one(!) issue (which should be summarized in the title). Otherwise the whole issue section gets to clutered.

1. maybe
2. I dont understand
3. maybe
4. no
