### ISSUE TITLE
Different icons for shuffle on/off etc.

### ISSUE THREAD

**Issue by Akmal02** [kabouzeid/phonograph-issue-tracker#66]
Icons on the bar that control play/pause etc should be clear. I suggest hat it should be more concise to tell whethet it is on or off. For example, the 'Shuffle' toggle should indicate two straight arrows for 'off' and two intersecting arrows for 'on'. Same goes for the 'Repeat' toggle'. Changing colors doesnt tell much. Gray and white sometimes looks no difference.

**Comment by kabouzeid** [comment]
Decided against that for now.
