### ISSUE TITLE
Lockscreen Madness

### ISSUE THREAD

**Issue by uudruid74** [kabouzeid/phonograph-issue-tracker#73]
When Phonograph is active, it messes with the lockscreen even when it shouldn't.

For example, if I turn off the 'show album art' switch I get my home screen background on the lockscreen instead of my lockscreen wallpaper.   The same happens when there is no album art to display.  I have to stop playback and completely remove the notification to get my lockscreen image back.

**Comment by kabouzeid** [comment]
Does that happen with other players?

**Comment by uudruid74** [comment]
No, this is the only one that screws up my lockscreen

**Comment by uudruid74** [comment]
Correction.  Some players do and act exactly like Phonograph.  Other players such as the one I'm using now, do not have this issue (but it doesn't offer any lockscreen integration at all).

**Comment by kabouzeid** [comment]
Well this seems like an issue with your ROM then... You could try disabling themes on your device, if you got any installed?

**Comment by uudruid74** [comment]
Will just use the other player the doesn't fuck up my lockscreen.

**Comment by xiprox** [comment]
👍👍

**Comment by okungnyo** [comment]
Your signature should be

Sent from my ImSpecialEveryoneLookAtMeMail
