### ISSUE TITLE
Annoying white flash when opening Phonograph (dark theme)

### ISSUE THREAD

**Issue by shaft17** [kabouzeid/phonograph-issue-tracker#77]
When selected "dark theme", Phonograph opens itself with a long animated white flash and switches then to dark colors.
Maybe try to check prior to animation, if dark or light is selected? If dark is selected, it would be better to choose a black screen for animation, looks way more fluent.

**Comment by kabouzeid** [comment]
I understand what you mean, but I cannot check prior the animation which theme is enabled.

**Comment by Xorok** [comment]
Not directly related but could you reconsider a splashscreen?
https://vid.me/PUw7

**Comment by xiprox** [comment]
lolnope. Please no. http://www.androiduipatterns.com/2015/08/splash-screen-with-any-other-name-is.html

**Comment by kabouzeid** [comment]
Sorry dude, I'm not a fan of splash screens at all :/
