### ISSUE TITLE
No lockscreen album art

### ISSUE THREAD

**Issue by MrHaPpY66** [kabouzeid/phonograph-issue-tracker#79]
The app will just stop playing the music at random times. I'm able to switch songs and press pause/play but the music progress bar doesn't move. Also the lockscreen album art doesn't appear. I'm running the app on an AT&T Galaxy Note 4(SM-N910A)

**Comment by MrHaPpY66** [comment]
Actually I solved the audio issue but the lockscreen problem still persists

**Comment by kabouzeid** [comment]
Do you have lockscreen album art enabled in Phonographs settings?

**Comment by MrHaPpY66** [comment]
Yes I do. I think it's an issue with Samsung devices because I've noticed the stock music app no longer shows album art when I updated to 5.1.1
