### ISSUE TITLE
Fastscroller unaccurate on small lists

### ISSUE THREAD

**Issue by pabsrocka** [kabouzeid/phonograph-issue-tracker#85]
In artist tab, when one-column grid size is selected, the scrollbar doesnt follow the finger. Its always behind the tap.

**Comment by pabsrocka** [comment]
PS: only happens when scrolling down. Scrolling up works as expected.

**Comment by kabouzeid** [comment]
see https://github.com/kabouzeid/phonograph-issue-tracker/issues/57
