### ISSUE TITLE
Some little bug

### ISSUE THREAD

**Issue by NikyNike** [kabouzeid/phonograph-issue-tracker#86]
- Qualche volta il cursore di scorrimento si blocca e non si muove più
- Non funziona la riproduzione senza intervalli
- Non mi mette la copertina dell'album nella schermata di blocco
- Ancora non supporta i testi delle canzoni

**Comment by kabouzeid** [comment]
English pls. Also proper title.

**Comment by okungnyo** [comment]
LOL

**Comment by okungnyo** [comment]
Google Translate:
* Sometimes the slider is locked and no longer moves
* Playback does not work without intervals
* I put the album art on the lock screen
* Still does not support lyrics

Understandable.

**Comment by xiprox** [comment]
This is not an issue of understandablity. Why should the dev bother with translation when the user didn't?

Plus, 2 and 3 aren't really all that understandable. And, these are 4 different issues, not one.

**Comment by NikyNike** [comment]
Scusate se non so scrivere in inglese e Google Traduttore non fa il suo dovere
Ma poi chi ti credi di essere?! Io ho l'applicazione tutta in italiano e pensavo che potevo segnalare i bug anche nella mia lingua
L'inglese lo capisco molto bene, ma non so usarlo per scrivere, e la traduzione fatta da google traduttore non ha senso rispetto a quello che volevo segnalare io
Scusa ancora la mia ignoranza, ma non siamo mica tutti sapienti come voi che conoscete 10 lingue e le sapete pure usare per comunicare con gli altri ...scusate >:(

**Comment by kabouzeid** [comment]
@xiprox I was just about to say exactly that ^^

**Comment by okungnyo** [comment]
LOL this guy must be a troll.

Hey Goombah, if you understand enough English for your rebuttals to be so precise, then you can make a bit more of an effort to copy and paste your text into Google Translate UNDERNEATH your Italian mumbo-jumbo. Is your IQ like 12?
