### ISSUE TITLE
The color in notifications panel is different from the color in the playing screen

### ISSUE THREAD

**Issue by MohamedHashem** [kabouzeid/phonograph-issue-tracker#96]
The colored notifications are not the same as the colored playing screen, It looks like the notifications use less pale colors than the colors in the playing screen. and btw colors are better in notifications panel

**Comment by MohamedHashem** [comment]
It's something like there's a different color detection algorithm in the notification panel player

**Comment by kabouzeid** [comment]
Thats how Googles Palette lib works. The images are loaded with different resolutions in different places which can cause different colors as the result of the color detecting algorithm.
