### ISSUE TITLE
Website in about section is wrong

### ISSUE THREAD

**Issue by ecols33** [kabouzeid/phonograph-issue-tracker#98]
[kabouzeid.de](http://kabouzeid.de) is down, however [kabouzeid.com](http://kabouzeid.com) is up

**Comment by kabouzeid** [comment]
thx

**Comment by Xorok** [comment]
Both are down atm. kabouzeid.com gives you an error, kabouzeid.de doesn't.

http://fs5.directupload.net/images/151109/rhhn5rvx.png

**Comment by ecols33** [comment]
@Xorok no kabouzeid.com is up: 
![screen shot 2015-11-15 at 4 51 36 pm](https://cloud.githubusercontent.com/assets/12535799/11171580/7936e91c-8bb9-11e5-9a2f-88562dc15102.png)

**Comment by Xorok** [comment]
Now it is, yes ;)
